services:
  trafficount:
    image: biloute02/trafficount:0.4.1-arm
    ports:
     - "8080:8080/tcp"
    devices:
     - "/dev/video0:/dev/video0"
    entrypoint:
     - python
     - "/trafficount/sources/main_counter.py"
    volumes:
     - "./video_writer:/trafficount/video_writer"
     - "./configuration:/trafficount/configuration"
    env_file:
     - pgclient.env
    restart: always # Redémarrer le conteneur au redémarrage
