services:
  trafficount:
    image: biloute02/trafficount:latest-cpu
    ports:
     - "8080:8080/tcp"
    devices:
     - "/dev/video0:/dev/video0"
    entrypoint:
     - python
     - "/trafficount/sources/main_counter.py"
    volumes:
     - ./video_writer:/trafficount/video_writer
    env_file:
     - pgclient.env
    restart: always
